#!/usr/bin/env python3
"""Verify artifact provenance and optionally rebuild German contract outputs."""

from __future__ import annotations

import argparse
import hashlib
import os
import re
import shutil
import subprocess
import sys
import tempfile
import unicodedata
import xml.etree.ElementTree as ET
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
from zipfile import ZipFile


ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "vertragsdokumente" / "artifact-manifest.sha256"
CONTRACTS = (
    "bautraegervertrag",
    "bautraegervertrag-marewald",
    "bautraegervertrag-lindenhain",
)
ZIP_MEMBERS = {
    "bautraegervertrag": (
        "01-wohnungsbautraegervertrag-mit-auflassung.pdf",
        "02-baubeschreibung-birkenpfuhl-komfort-b4.pdf",
    ),
    "bautraegervertrag-marewald": (
        "01-wohnungsbautraegervertrag-mit-auflassung.pdf",
        "02-baubeschreibung-marewald-komfort-c.pdf",
    ),
    "bautraegervertrag-lindenhain": (
        "01-wohnungsbautraegervertrag-mit-auflassung.pdf",
        "02-baubeschreibung-lindenhain-komfort.pdf",
    ),
}
REQUIRED_TOOLS = ("pandoc", "weasyprint", "perl", "zip", "pdftotext", "pdfinfo")
WORD_NS = "http://schemas.openxmlformats.org/wordprocessingml/2006/main"
CORE_NS = {
    "cp": "http://schemas.openxmlformats.org/package/2006/metadata/core-properties",
    "dc": "http://purl.org/dc/elements/1.1/",
}
PROVENANCE_PREFIX = "btv-source-sha256:"


def fail(message: str) -> None:
    print(f"FAIL contract builds: {message}", file=sys.stderr)
    raise SystemExit(1)


def protected_paths() -> list[Path]:
    paths = [Path("scripts/build_bilingual_contracts.py")]
    for name in CONTRACTS:
        base = Path("vertragsdokumente") / name
        paths.extend(
            [
                base / "build.sh",
                base / "build/pdf-template.html",
                base / "build/pagebreak.lua",
                base / "build/style.css",
                base / f"{name}.md",
                base / f"{name}.pdf",
                base / f"{name}.docx",
                base / f"{name}-einzel-pdfs.zip",
                base / f"{name}-de-en.html",
                base / f"{name}-de-en.pdf",
                base / f"{name}-de-en.docx",
            ]
        )
    return sorted(paths, key=lambda path: path.as_posix())


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def expected_hashes() -> dict[str, str]:
    result: dict[str, str] = {}
    for relative in protected_paths():
        absolute = ROOT / relative
        if not absolute.is_file():
            fail(f"protected file is missing: {relative}")
        result[relative.as_posix()] = sha256(absolute)
    return result


def read_manifest() -> dict[str, str]:
    if not MANIFEST.is_file():
        fail(f"artifact manifest is missing: {MANIFEST.relative_to(ROOT)}")
    result: dict[str, str] = {}
    for line_number, raw_line in enumerate(
        MANIFEST.read_text(encoding="utf-8").splitlines(), start=1
    ):
        if not raw_line or raw_line.startswith("#"):
            continue
        match = re.fullmatch(r"([0-9a-f]{64})  (.+)", raw_line)
        if match is None:
            fail(f"malformed manifest line {line_number}")
        digest, relative = match.groups()
        path = Path(relative)
        if path.is_absolute() or ".." in path.parts:
            fail(f"unsafe manifest path on line {line_number}: {relative}")
        if relative in result:
            fail(f"duplicate manifest path on line {line_number}: {relative}")
        result[relative] = digest
    return result


def verify_manifest(*, check_artifacts: bool = True) -> None:
    if check_artifacts:
        verify_zip_structures()
        verify_bilingual_provenance()
    expected = expected_hashes()
    recorded = read_manifest()
    missing = sorted(expected.keys() - recorded.keys())
    extra = sorted(recorded.keys() - expected.keys())
    changed = sorted(
        path for path in expected.keys() & recorded.keys() if expected[path] != recorded[path]
    )
    if missing:
        fail(f"manifest lacks protected files: {', '.join(missing)}")
    if extra:
        fail(f"manifest contains unexpected files: {', '.join(extra)}")
    if changed:
        fail(
            "source, build rule or artifact changed without a verified rebuild: "
            + ", ".join(changed)
        )
    print(f"check_contract_builds: manifest ok ({len(expected)} protected files)")


def write_manifest() -> None:
    rebuild_contracts()
    verify_zip_structures()
    verify_bilingual_provenance()
    hashes = expected_hashes()
    lines = [
        "# Generated by: python3 scripts/check_contract_builds.py --write",
        "# Update only after German and bilingual artifacts have been rebuilt and checked.",
    ]
    lines.extend(f"{digest}  {path}" for path, digest in hashes.items())
    MANIFEST.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"check_contract_builds: wrote {MANIFEST.relative_to(ROOT)}")


def canonical_text(value: str) -> str:
    value = unicodedata.normalize("NFC", value).replace("\u00ad", "")
    value = re.sub(r"(?m)^\s*\d+\s*$", "", value)
    value = re.sub(r"(?<=\w)-\s*\n\s*(?=\w)", "", value)
    return re.sub(r"\s+", " ", value).strip()


def pdf_text(path: Path) -> str:
    result = subprocess.run(
        ["pdftotext", "-enc", "UTF-8", str(path), "-"],
        check=True,
        capture_output=True,
        text=True,
    )
    return canonical_text(result.stdout)


def docx_text(path: Path) -> str:
    with ZipFile(path) as archive:
        try:
            document = archive.read("word/document.xml")
        except KeyError:
            fail(f"DOCX lacks word/document.xml: {path}")

    root = ET.fromstring(document)
    qn = lambda name: f"{{{WORD_NS}}}{name}"
    paragraphs: list[str] = []
    for paragraph in root.iter(qn("p")):
        parts: list[str] = []
        for node in paragraph.iter():
            if node.tag == qn("t"):
                parts.append(node.text or "")
            elif node.tag == qn("tab"):
                parts.append("\t")
            elif node.tag in {qn("br"), qn("cr")}:
                parts.append("\n")
        paragraphs.append("".join(parts))
    return canonical_text("\n".join(paragraphs))


def archive_pdf_texts(path: Path, scratch: Path) -> dict[str, str]:
    result: dict[str, str] = {}
    scratch.mkdir(parents=True, exist_ok=True)
    with ZipFile(path) as archive:
        names = sorted(name for name in archive.namelist() if not name.endswith("/"))
        for index, name in enumerate(names):
            if not name.lower().endswith(".pdf"):
                fail(f"unexpected non-PDF ZIP member in {path.name}: {name}")
            extracted = scratch / f"{index:02d}-{Path(name).name}"
            extracted.write_bytes(archive.read(name))
            result[name] = pdf_text(extracted)
    return result


def verify_zip_structures() -> None:
    for name, expected_members in ZIP_MEMBERS.items():
        path = ROOT / "vertragsdokumente" / name / f"{name}-einzel-pdfs.zip"
        with ZipFile(path) as archive:
            members = [item.filename for item in archive.infolist()]
            if len(members) != len(set(members)):
                fail(f"ZIP contains duplicate member names: {path.name}")
            if tuple(sorted(members)) != tuple(sorted(expected_members)):
                fail(
                    f"ZIP member list is not exact for {path.name}: "
                    + ", ".join(members)
                )
            for item in archive.infolist():
                member = Path(item.filename)
                if item.is_dir() or member.name != item.filename or item.file_size == 0:
                    fail(f"unsafe, nested or empty ZIP member in {path.name}: {item.filename}")
    print(f"check_contract_builds: ZIP structures ok ({len(ZIP_MEMBERS)} archives)")


def extract_provenance(value: str, label: str) -> str:
    matches = set(re.findall(rf"{PROVENANCE_PREFIX}([0-9a-f]{{64}})", value))
    if len(matches) != 1:
        fail(f"missing or ambiguous bilingual source provenance: {label}")
    return matches.pop()


def html_provenance(path: Path) -> str:
    return extract_provenance(path.read_text(encoding="utf-8"), path.name)


def pdf_provenance(path: Path) -> str:
    if shutil.which("pdfinfo") is None:
        fail("missing build dependency: pdfinfo")
    result = subprocess.run(
        ["pdfinfo", str(path)], check=True, capture_output=True, text=True
    )
    return extract_provenance(result.stdout, path.name)


def docx_provenance(path: Path) -> str:
    with ZipFile(path) as archive:
        try:
            core = ET.fromstring(archive.read("docProps/core.xml"))
        except KeyError:
            fail(f"DOCX lacks docProps/core.xml: {path.name}")
    metadata = " ".join(
        filter(
            None,
            [
                core.findtext("dc:description", default="", namespaces=CORE_NS),
                core.findtext("cp:keywords", default="", namespaces=CORE_NS),
            ],
        )
    )
    return extract_provenance(metadata, path.name)


def verify_bilingual_provenance() -> None:
    for name in CONTRACTS:
        directory = ROOT / "vertragsdokumente" / name
        expected = sha256(directory / f"{name}.md")
        artifacts = {
            "HTML": html_provenance(directory / f"{name}-de-en.html"),
            "PDF": pdf_provenance(directory / f"{name}-de-en.pdf"),
            "DOCX": docx_provenance(directory / f"{name}-de-en.docx"),
        }
        stale = [kind for kind, digest in artifacts.items() if digest != expected]
        if stale:
            fail(
                f"stale bilingual artifacts for {name}: {', '.join(stale)} "
                f"do not match {name}.md"
            )
    print(
        "check_contract_builds: bilingual provenance ok "
        f"({len(CONTRACTS) * 3} artifacts)"
    )


def compare_text(label: str, committed: str, rebuilt: str) -> None:
    if committed != rebuilt:
        fail(f"stale or divergent generated content: {label}")


def compare_contract(name: str, temporary_root: Path) -> tuple[int, str]:
    committed_dir = ROOT / "vertragsdokumente" / name
    rebuilt_dir = temporary_root / name
    shutil.copytree(committed_dir, rebuilt_dir)

    build_script = rebuilt_dir / "build.sh"
    build = subprocess.run(
        [str(build_script)],
        cwd=rebuilt_dir,
        check=False,
        capture_output=True,
        text=True,
    )
    if build.returncode != 0:
        details = "\n".join(
            part.strip() for part in (build.stdout, build.stderr) if part.strip()
        )
        fail(f"rebuild failed for {name}:\n{details}")

    committed_pdf = committed_dir / f"{name}.pdf"
    rebuilt_pdf = rebuilt_dir / f"{name}.pdf"
    compare_text(f"{name}.pdf", pdf_text(committed_pdf), pdf_text(rebuilt_pdf))

    committed_docx = committed_dir / f"{name}.docx"
    rebuilt_docx = rebuilt_dir / f"{name}.docx"
    compare_text(f"{name}.docx", docx_text(committed_docx), docx_text(rebuilt_docx))

    archive_name = f"{name}-einzel-pdfs.zip"
    committed_zip = archive_pdf_texts(
        committed_dir / archive_name, temporary_root / f"committed-{name}"
    )
    rebuilt_zip = archive_pdf_texts(
        rebuilt_dir / archive_name, temporary_root / f"rebuilt-{name}"
    )
    if committed_zip.keys() != rebuilt_zip.keys():
        fail(f"ZIP member list differs after rebuild: {archive_name}")
    for member in committed_zip:
        compare_text(
            f"{archive_name}:{member}", committed_zip[member], rebuilt_zip[member]
        )
    build_log = "\n".join(
        part.strip() for part in (build.stdout, build.stderr) if part.strip()
    )
    return 2 + len(committed_zip), build_log


def build_worker_count() -> int:
    raw_value = os.environ.get("BTV_BUILD_WORKERS", str(len(CONTRACTS)))
    try:
        value = int(raw_value)
    except ValueError:
        fail(f"BTV_BUILD_WORKERS must be an integer, got: {raw_value}")
    return max(1, min(len(CONTRACTS), value))


def rebuild_contracts() -> None:
    missing = [tool for tool in REQUIRED_TOOLS if shutil.which(tool) is None]
    if missing:
        fail(f"missing build dependencies: {', '.join(missing)}")

    artifact_count = 0
    with tempfile.TemporaryDirectory(prefix="btv-contract-builds-") as temporary:
        temporary_root = Path(temporary)
        with ThreadPoolExecutor(max_workers=build_worker_count()) as executor:
            futures = {
                name: executor.submit(compare_contract, name, temporary_root)
                for name in CONTRACTS
            }
            for name in CONTRACTS:
                compared, build_log = futures[name].result()
                artifact_count += compared
                if build_log:
                    print(f"[{name}]\n{build_log}")

    print(
        "check_contract_builds: ok "
        f"({len(CONTRACTS)} contracts, {artifact_count} content comparisons)"
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument(
        "--rebuild",
        action="store_true",
        help="Also rebuild German PDF, DOCX and ZIP files in a temporary directory.",
    )
    mode.add_argument(
        "--write",
        action="store_true",
        help="After a successful local rebuild, rewrite the SHA-256 manifest.",
    )
    args = parser.parse_args()

    if args.write:
        write_manifest()
        verify_manifest(check_artifacts=False)
        return

    verify_manifest()
    if args.rebuild:
        rebuild_contracts()


if __name__ == "__main__":
    main()
